# Generated by Django 2.2.16 on 2021-03-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0057_resourcebase_metadata_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='CswService',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.ResourceBase')),
                ('service_type', models.CharField(choices=[('WMS', 'OGC:WMS'), ('WCS', 'OGC:WCS'), ('WFS', 'OGC:WFS'), ('WMTS', 'OGC:WMTS'), ('OTHER', 'OTHER')], max_length=32)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.resourcebase',),
        ),
    ]
