# Generated by Django 2.2.16 on 2021-03-09 18:13

from django.db import migrations, models
import django.db.models.deletion


def change_cswtype(apps, schema_editor):
    Resources = apps.get_model('base', 'ResourceBase')
    Resources.objects.filter(csw_type='service').update(csw_type="cswservice")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csw_services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_cswtype),
    ]
